### ISSUE TITLE
Logic Problem 2 - String splitting

### ISSUE THREAD

**Issue by vinceynhz** [CarterLankford/MentorExercises#16]
The `split(…)` method of the `String` class in Java, serves to do that: split a string using a regular expression as a delimiter (we’ll see what regular expressions are later if you’re not familiar with them already). The method returns an array of Strings of the pieces after the split, without the delimiter strings. 

For example, let’s take the string `"boo:and:foo"`:

- If we split using the semicolon (`":"`) as delimiter, we’ll get the following pieces: `"boo"`, `"and"`, `"foo"` in an array of length 3.
- If we split using the character `"o"` as delimiter we’ll get the following pieces: `"b"`, `""` (an empty string since there’s no characters between the two `"o"`'s of `"boo"`), `":and:f"` in an array of length 3 as well. The last two `"oo"`'s do not give an empty string (as for `"boo"`) since the method ignores any trailing empty strings.

And here is the question:

For each the following strings, how many elements will there be in the array returned by `"split()"` using `"/"` as delimiter? And of course, what pieces would there be in each array?

1.	`"/"`
2.	`"/resource"`
3.	`"/resource/path"`
4.	`"resource"`

I would encourage you to answer the questions avoiding coding using only your reasoning powers and the definition and examples shown above. The full documentation of the method is here: https://docs.oracle.com/javase/7/docs/api/java/lang/String.html#split(java.lang.String)

**Comment by CarterLankford** [comment]
1.) Would return one element, empty string:  [""]
2.) Would return one element:  ["resource"]
3.) Would return two elements: ["resource", "path"]
4.) Would return one element:  ["resource"]

**Comment by vinceynhz** [comment]
Alright, let's validate it! Write a simple class with main to run these scenarios. Print out whatever `split()` returns.

1. Did you responses match what the code is doing?
2. If not, why? Explain the differences using the documentation as a reference

**Comment by CarterLankford** [comment]
> 1. Did your responses match what the code is doing? 

No it doesn't. 

> 2. If not, why? Explain the difference using the documentation as a reference

In short if the delimiter is found it will include an empty string into the array, but as per the documentation "Trailing empty strings are therefore not included in the resulting array.". So all trailing delimiters found after the first will not be added into the array as empty strings. Code has been added in the pull request:  https://github.com/CarterLankford/MentorExercises/pull/22

**Comment by vinceynhz** [comment]
This is not correct:
> In short if the delimiter is found it will include an empty string into the array, but as per the documentation "Trailing empty strings are therefore not included in the resulting array.". So all trailing delimiters found after the first will not be added into the array as empty strings. Code has been added in the pull request: #22

The delimiter is used to break a big "working" string onto smaller strings, cutting every time you see the delimiter. See this example. Let's consider this string
```java
"some~delimited~string"
```
When we call the `split` method over it, using `"~"` as delimiter, the string will be broken 2 times (one for each `"~"` character found:

```java
// initial state:
"some~delimited~string"
'--- working string---'

//1st break:
"some" + "delimited~string"
         '------ ws ------'

// 2nd break:
"some" + "delimited" + "string"
                       '- ws -'
```

So the final array is:
```java
["some", "delimited", "string"]
```
Please note that every time the `"~"` character is found a new string is created with all the preceding characters, and a new version of the working string is created with the characters left after the cut.

---

Empty strings occur when there are no characters on the working string before finding a delimiter. Consider the following example:
```java
"~some~delimited~~string"
```
In this case there will be 4 breaks, one per each `"~"` character:
```java
// initial state
"~some~delimited~~string"
'--- working string ---'

// 1st break - there were no characters before finding the first delimiter on the working string
"" + "some~delimited~~string"
     '--- working string ---'

// 2nd break 
"" + "some" + "delimited~~string"
              '- working string -'

// 3rd break
"" + "some" + "delimited" + "~string"
                            '-- ws --'

// 4th break - there were no characters before finding the next delimiter on the working string
"" + "some" + "delimited" + "" + "string"
                                 '- ws -'
```
Final array:
```java
["", "some", "delimited, "", "string"]
```

---

On the case of having multiple delimiters at the end of the working string, all empty strings that may occur at the end of the final array will be ignored. See this example in which there will be 6 cuts (one pear each `"~"`):
```java
// initial state:
"delimited~string~~~~~"
'--- working string---'

//1st break:
"delimited" + "string~~~~~"
              '-- working string --'

//2nd break:
"delimited" + "string" + "~~~~"
                         '-ws-'

//3rd break:
"delimited" + "string" + "" + "~~~"
                              '-ws-'

//4th break:
"delimited" + "string" + "" + "" + "~~"
                                   '-ws-'

//5th break:
"delimited" + "string" + "" + "" + "" + "~"
                                        '-ws-'

//6th break:
"delimited" + "string" + "" + "" + "" + "" + ""
                                             '-ws-'
                        '- ignored empty strings -'
```
So the final array is:
```java
["delimited", "string"]
```
